### ISSUE TITLE
EACCES error when installing the Matano CLI

### ISSUE THREAD

**Issue by niheconomoum** [matanolabs/matano#1]
I am running Ubuntu 20.04 on Windows via WSL 1.

I have installed node.js v12.22.12 via the NodeSource PPA per https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04.

Running `make install` per https://www.matano.dev/docs/installation, I get the following error:

```
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

The relevant NPM logs are attached.

[2022-08-12T14_24_33_045Z-debug.log](https://github.com/matanolabs/matano/files/9318496/2022-08-12T14_24_33_045Z-debug.log)
[2022-08-12T14_24_33_060Z-debug.log](https://github.com/matanolabs/matano/files/9318512/2022-08-12T14_24_33_060Z-debug.log)

**Comment by Samrose-Ahmed** [comment]
Hi, thanks for the issue, this is due to installing in the system node modules. We should likely change the install script to use the `--user` npm flag.

The repo is under heavy development and we'll be making significant changes in the next weeks. Feel free to join our [Discord](https://discord.gg/YSYfHMbfZQ) for updates.

**Comment by Samrose-Ahmed** [comment]
Closing as we now provide prebuilt binaries through [a GitHub Release](https://github.com/matanolabs/matano/releases/tag/nightly) without a Node/NPM dependency. (#3)
