### ISSUE TITLE
[Feature Request] Allow Custom Tags on all taggable resources

### ISSUE THREAD

**Issue by zbmowrey** [matanolabs/matano#10]
# What

Allow users to apply their own custom AWS tags to all taggable resources.

# Why
Business/Enterprise clients will need the ability to determine ownership and costs for this application. 

# How

Add support for an optional **tags** property in matano.config.yml which allows users to input a list of key:value pairs which will be applied to all taggable resources in all Matano stacks.

**Comment by Samrose-Ahmed** [comment]
Implemented in https://github.com/matanolabs/matano/commit/514b60a7d7888ef3e192252ed338987dc316ae29 and docs in https://www.matano.dev/docs/reference/matano-configuration-file

like:
```yml
aws_tags:
  cost_center: "80432"
```
