### ISSUE TITLE
Snyk managed integration new URL endpoint.

### ISSUE THREAD

**Issue by ubpomelo** [matanolabs/matano#189]
According to Snyk API Docs and what [Matano](https://snyk.docs.apiary.io/#reference/reporting-api/issues/get-list-of-issues?console=1)  integration supports, we found out that issues [endpoint](https://github.com/matanolabs/matano/blob/116b9184b6eb1032da9486834f0a4fca7a5857d3/lib/rust/log_puller/src/pullers/snyk.rs#L212) is missing _v1_ path. 
The right path would be: `https://api.snyk.io/v1/reporting/issues/`. Also note that after dates is a missing _&_ and query is failing. 

I've tested it locally and it works good.

**Comment by shaeqahmed** [comment]
Thanks for the catch, fixed.
