### ISSUE TITLE
bug: Init fails if there is not a default VPC in the account

### ISSUE THREAD

**Issue by timoguin** [matanolabs/matano#43]
## What?

When running `matano init`, the wizard fails while initializing the AWS environment because it can't find a default VPC.

Error output:

```
Initializing AWS environment... (1/3) ›   Error: An error occurred: Could not find any VPCs matching {"account":"111111111111","region":"us-east-1","filter":{"is-default":"true"}}
```

## Fix

- It should prompt for a VPC ID.
- Even better (next iteration), it should fetch a list of VPCs and provide a selection prompt.

**Comment by Samrose-Ahmed** [comment]
Thx. Same as #34. We actually don't use VPC's  anywhere in the architecture currently so we'll just remove requiring VPC. If/when we need VPC's we can add the prompt/select.

Just pushed c29c8b2bba7adddefda1b34f789b73ced4dafbfd which doesn't require the VPC anymore.

**Comment by timoguin** [comment]
> Thx. Same as #34. We actually don't use VPC's  anywhere in the architecture currently so we'll just remove requiring VPC. If/when we need VPC's we can add the prompt/select.
> 
> Just pushed c29c8b2bba7adddefda1b34f789b73ced4dafbfd which doesn't require the VPC anymore.

Thanks for that. I do have interest in running things within VPCs, but I had already seen that I was going to need to create VPC endpoints for all the various AWS services (otherwise we're just going out to the internet anyway).

Once we're adding more sources we will definitely want that.

Until then though! 💪

Thanks again!

**Comment by Samrose-Ahmed** [comment]
Awesome, feel free to create an issue for VPC support, should be easy to add in.
