### ISSUE TITLE
bug(devex): Building rust targets fails if local-assets dir doesn't exist

### ISSUE THREAD

**Issue by timoguin** [matanolabs/matano#44]
## What?

The `make build-rust` target fails on the last copy step if there is not a `local-assets` directory.

Once I created the `local-assets` directory, the command was able to succeed.

**Comment by Samrose-Ahmed** [comment]
Fixed in https://github.com/matanolabs/matano/commit/4d3539991aa4fb27e1830000cef656541efcef40 .
