### ISSUE TITLE
"Error: command bootstrap not found" when bootstrapping the AWS account

### ISSUE THREAD

**Issue by niheconomoum** [matanolabs/matano#5]
I am running Ubuntu 20.04 on Windows via WSL 1.

I have installed node.js v12.22.12 via the Node Version Manager per https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04.

I have installed the Matano CLI and created the configuration directory.

When I run `matano bootstrap`, I get the following error:

```sh
xenophonf@l0000000d:~/src/matano/my-matano-config$ matano bootstrap
(node:24682) SyntaxError Plugin: matano: Unexpected token '.'
module: @oclif/core@1.9.5
task: toCached
plugin: matano
root: /home/xenophonf/src/matano/cli
See more details with DEBUG=*
(node:24682) SyntaxError Plugin: matano: Unexpected token '.'
module: @oclif/core@1.9.5
task: toCached
plugin: matano
root: /home/xenophonf/src/matano/cli
See more details with DEBUG=*
(node:24682) SyntaxError Plugin: matano: Unexpected token '?'
module: @oclif/core@1.9.5
task: toCached
plugin: matano
root: /home/xenophonf/src/matano/cli
See more details with DEBUG=*
 ›   Error: command bootstrap not found
```

**Comment by Samrose-Ahmed** [comment]
Thanks for the issue. Looks like it is erroring on optional chaining syntax (?.). 

You can upgrade your node version to fix this. We should either change our typescript target to support node12 or update the docs to support node>=14.

**Comment by Samrose-Ahmed** [comment]
The CLI now supports node 12.
