### ISSUE TITLE
Managed log source for S3 Inventory Reports

### ISSUE THREAD

**Issue by timoguin** [matanolabs/matano#66]
Add support for managing S3 Inventory Reports.

## Considerations

Inventory reports can be delivered in one of three formats: CSV, ORC, or Parquet. Since this isn't the only AWS service that can deliver data in Parquet (or ORC) format, we should support ingesting them, especially considering columnar format support will continue to expand to other services.

Inventory reports can be delivered hourly or weekly.

The object metadata to include in the reports is configurable, so we'll need to be sure to handle any missing keys/values.

## References

- https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-inventory.html
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-inventory-athena-query.html

**Comment by Samrose-Ahmed** [comment]
- Shipped in https://github.com/matanolabs/matano/pull/73
- Docs at https://www.matano.dev/docs/log-sources/managed-log-sources/aws/s3-inventory-report
