### ISSUE TITLE
"View the complete installation instructions" link missing

### ISSUE THREAD

**Issue by francescor** [matanolabs/matano#67]
in  https://github.com/matanolabs/matano/blob/main/README.md the link (https://www.matano.dev/docs/installation ) to "View the complete installation instructions" is not working

**Comment by francescor** [comment]
I guess it should be https://www.matano.dev/docs/getting-started#installation

**Comment by francescor** [comment]
https://github.com/matanolabs/matano/pull/68

**Comment by shaeqahmed** [comment]
#68 merged, thank you!!
