### ISSUE TITLE
Managed log source for Snyk audit logs

### ISSUE THREAD

**Issue by timoguin** [matanolabs/matano#71]
Add support for managing Snyk audit logs.

## Considerations

Snyk has a poll-based API for retrieving audit logs at both the organization and group levels.

Webhooks are currently in beta. It is unclear to me from the docs if there is variance between that data that comes from webhooks versus the API.

These are only available for business or enterprise customers.

## References

- [Audit Logs User docs](https://docs.snyk.io/user-and-group-management/managing-users-and-permissions/audit-logs)
- [Audit Logs API reference](https://snyk.docs.apiary.io/#reference/audit-logs)
- [Webhooks User docs](https://docs.snyk.io/snyk-api-info/snyk-webhooks)
- [Webhooks API docs](https://snyk.docs.apiary.io/#reference/webhooks/get-organization-level-audit-logs)

**Comment by Samrose-Ahmed** [comment]
- Shipped in https://github.com/matanolabs/matano/pull/74
- Docs at https://www.matano.dev/docs/log-sources/managed-log-sources/snyk

As per Shaeq, looks like all the data is contained in the audit logs.
