### ISSUE TITLE
Error when parsing AWS ELB/ALB logs

### ISSUE THREAD

**Issue by shaeqahmed** [matanolabs/matano#88]
Reported by @timoguin

**Comment by shaeqahmed** [comment]
> I just deployed to a new account with a hefty bucket for ELB logs (primarily ALB). I seem to be dealing with a silent failure with the transformer. I'm still seeing a 100% success rate for the Lambda, but the CW Logs are full of ERROR transformer: Failed to parse matano timestamp. Thre are also some ERROR transformer: USER_ERROR: Failed at FindUnionVariant, likely schema issue..

Nothing is making it into any DLQs, but nothing is making it into the realtime bucket either (and ultimate not the lake bucket). So it seems events are silently getting dropped.

**Comment by Samrose-Ahmed** [comment]
Looks like we need to convert the `.ts` from the grok expression to a timestamp type.

https://github.com/matanolabs/matano/blob/main/data/managed/log_sources/aws_elb/log_source.yml#L162

A simple `.ts = to_timestamp!(.ts)` should fix.

**Comment by timoguin** [comment]
@Samrose-Ahmed I'm looking at the referenced line. Do you have a quick snippet I can add to the VCL to test this?

**Comment by Samrose-Ahmed** [comment]
If you can edit source, add `.ts = to_timestamp!(.ts)` to line 178 https://github.com/matanolabs/matano/blob/main/data/managed/log_sources/aws_elb/log_source.yml#L178 here.

I'll commit the change after testing as well.

**Comment by Samrose-Ahmed** [comment]
That fixes timestamp still seeing a schema mismatch, failing log:

```json
{
    "aws": {
        "elb": {
            "action_executed": [
                "forward",
                "redirect"
            ],
            "backend": {
                "http": {
                    "response": {
                        "status_code": 200
                    }
                },
                "ip": "10.0.0.1",
                "port": "80"
            },
            "backend_processing_time": {
                "sec": 0.001
            },
            "matched_rule_priority": "0",
            "name": "app/my-loadbalancer/50dc6c495c0c9188",
            "protocol": "http",
            "request_processing_time": {
                "sec": 0
            },
            "response_processing_time": {
                "sec": 0
            },
            "target_group": {
                "arn": "arn:aws:elasticloadbalancing:us-east-2:123456789012:targetgroup/my-targets/73e2d6bc24d8a067"
            },
            "target_port": "10.0.0.1:80",
            "target_status_code": "200",
            "trace_id": "Root=1-58337262-36d228ad5d99923122bbe354",
            "type": "http"
        }
    },
    "cloud": {
        "provider": "aws"
    },
    "ecs": {
        "version": "8.5.0"
    },
    "event": {
        "category": "web",
        "end": "2018-07-02T22:23:00.186641Z",
        "kind": "event",
        "outcome": "success",
        "start": "2018-07-02T22:22:48.364000Z"
    },
    "http": {
        "request": {
            "body": {
                "bytes": 34
            },
            "method": "GET"
        },
        "response": {
            "body": {
                "bytes": 366
            },
            "status_code": 200
        },
        "version": "1.1"
    },
    "source": {
        "address": "192.168.131.39",
        "ip": "192.168.131.39",
        "port": 2817
    },
    "trace": {
        "id": "Root=1-58337262-36d228ad5d99923122bbe354"
    },
    "ts": "2018-07-02T22:23:00.186641Z",
    "url": {
        "domain": "www.example.com",
        "original": "http://www.example.com:80/",
        "path": "/",
        "port": 80,
        "scheme": "http"
    },
    "user_agent": {
        "original": "curl/7.46.0"
    }
}
```

Looks like the `aws.elb.backend.port` is a string when it should be number.

Looks like vrl doesn't support `POSINT` in grok, should just use NUMBER

**Comment by timoguin** [comment]
I can confirm that adding the `.ts = to_timestamp!(.ts)` line took care of the timestamp issue, but, like you mentioned, I'm still seeing the schema issue now.

**Comment by timoguin** [comment]
@Samrose-Ahmed That's beyond my VRL-abilities at this time of night. Let me know what tweaks I should make, and I'll get it tested in production.

**Comment by Samrose-Ahmed** [comment]
Just pushed out https://github.com/matanolabs/matano/commit/d18b4f07885aeccbcda0c0f13c7ce12138e91886 which I've now confirmed to work with my test data. Let me know if there's any issues.

**Comment by timoguin** [comment]
@Samrose-Ahmed Aaaaand now I have a million events in my `aws_elb` table. So I think that might have done the trick. ;-)
