### ISSUE TITLE
Generic equivalent?

### ISSUE THREAD

**Issue by dpnishant** [matanolabs/matano#9]
This is not really an "issue". I just want to thank you for open-sourcing this interesting project. I have been thinking on the same lines but a vendor neutral alternative. Do you think there could be an vendor neutral equivalent for this project? Something that can be deployed across cloud providers as well bare-metal (Kubernetes)? Do you think there are equivalent alternatives for the AWS components that can be replaced with CNCF projects and/or FOSS projects? That would be really awesome and would probably have a much wider adoption IMHO.

Its perfectly fine though if you want to be AWS specific. :) Happy to chat further.

**Comment by Samrose-Ahmed** [comment]
Thanks for the question, Nishant. Here's our thinking:

- We definitely plan on supporting other clouds (e.g. Azure, GCP).
- As for complete self hosting/Kubernetes, we're not against it but there are some characteristics that make it a low priority.
   - One of the core goals of our project is being serverless/zero ops, including as an open source project. It's not really feasible to make a serverless system without relying on managed services. Having to maintain every service that goes into Matano would make it a very different experience.

It's still very early days, so we might adapt our plans, but that's how we see things right now.

**Comment by dpnishant** [comment]
Understood. Thanks for the reply. 👍🏻
